### ISSUE TITLE
Bug: Use github to login without public email

### ISSUE THREAD

**Issue by fcevado** [dailydrip/firestorm#47] opened 2017-03-24 16:29 UTC
![captura de tela 2017-03-24 as 09 26 27](https://cloud.githubusercontent.com/assets/9992984/24303746/eda22688-1095-11e7-97cc-5d8173e2a87f.png)

**Comment by Hostert** [comment] 2017-03-25 03:35
Same here, bug confirmed.

**Comment by Trevoke** [comment] 2017-03-25 13:17
Thanks for dogfooding and reporting this! 

For now, the email address is required if you want to receive emails, and requiring this email address is less effort than creating a settings page. Which, by the way, @knewter, I haven't found an issue / story for the settings page, do we have one? That should definitely be in before beta.

While we are in pre-alpha, you will need to temporarily make your Github email public before you log in to Firestorm; you can set it to private again after you've logged in. We're sorry about the inconvenience (and about using this trite expression).

This is a duplicate of #40 , so I will close this issue.

**Closed by Trevoke** 2017-03-25 13:17 UTC
